P=atomic_append
TLPI_LIB_PATH=../../../TLPI/tlpi-dist/lib
OBJECTS= $(TLPI_LIB_PATH)/error_functions.o $(TLPI_LIB_PATH)/get_num.o
CFLAGS= -I$(TLPI_LIB_PATH) -g -Wall -std=gnu11
LDLIBS=
CC=gcc

$(P): $(OBJECTS)
